name: Build and package GitHub Action
on:
  push

jobs:
  build-action-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
#      - run: npm ci
      - run: npm install
      - run: npm run-script build-action
      - uses: tool3/ncc@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: 'index.js'